# Generated by Django 5.2.7 on 2026-05-01 01:45

import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('state_code', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=2)),
                ('type', models.CharField(blank=True, max_length=191, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('parent_id', models.BigIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('native', models.CharField(blank=True, max_length=255, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, db_comment='IANA timezone identifier (e.g., America/New_York)', max_length=255, null=True)),
                ('translations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('flag', models.SmallIntegerField()),
                ('wikidataid', models.CharField(blank=True, db_column='wikiDataId', db_comment='Rapid API GeoDB Cities', max_length=255, null=True)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('iso3', models.CharField(blank=True, max_length=3, null=True)),
                ('numeric_code', models.CharField(blank=True, max_length=3, null=True)),
                ('iso2', models.CharField(blank=True, max_length=2, null=True)),
                ('phonecode', models.CharField(blank=True, max_length=255, null=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('currency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('currency_symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('tld', models.CharField(blank=True, max_length=255, null=True)),
                ('native', models.CharField(blank=True, max_length=255, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('gdp', models.BigIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('subregion', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('area_sq_km', models.FloatField(blank=True, null=True)),
                ('postal_code_format', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code_regex', models.CharField(blank=True, max_length=255, null=True)),
                ('timezones', models.TextField(blank=True, null=True)),
                ('translations', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('emoji', models.CharField(blank=True, max_length=191, null=True)),
                ('emojiu', models.CharField(blank=True, db_column='emojiU', max_length=191, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('flag', models.SmallIntegerField()),
                ('wikidataid', models.CharField(blank=True, db_column='wikiDataId', db_comment='Rapid API GeoDB Cities', max_length=255, null=True)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('translations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('flag', models.SmallIntegerField()),
                ('wikidataid', models.CharField(blank=True, db_column='wikiDataId', db_comment='Rapid API GeoDB Cities', max_length=255, null=True)),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=2)),
                ('fips_code', models.CharField(blank=True, max_length=255, null=True)),
                ('iso2', models.CharField(blank=True, max_length=255, null=True)),
                ('iso3166_2', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=191, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('parent_id', models.BigIntegerField(blank=True, null=True)),
                ('native', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('timezone', models.CharField(blank=True, db_comment='IANA timezone identifier (e.g., America/New_York)', max_length=255, null=True)),
                ('translations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('flag', models.SmallIntegerField()),
                ('wikidataid', models.CharField(blank=True, db_column='wikiDataId', db_comment='Rapid API GeoDB Cities', max_length=255, null=True)),
                ('population', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subregions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('translations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('flag', models.SmallIntegerField()),
                ('wikidataid', models.CharField(blank=True, db_column='wikiDataId', db_comment='Rapid API GeoDB Cities', max_length=255, null=True)),
            ],
            options={
                'db_table': 'subregions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha de actualización')),
                ('descripcion', models.TextField(blank=True, db_comment='Descripción', default=None, null=True)),
                ('value', models.TextField(db_comment='Valor')),
                ('name', models.CharField(db_comment='Nombre', max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='TipoColaborador',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha de actualización')),
                ('descripcion', models.TextField(blank=True, db_comment='Descripción', default=None, null=True)),
                ('code', models.CharField(db_comment='Código', max_length=100, primary_key=True, serialize=False)),
                ('status', models.ForeignKey(blank=True, db_comment='Estado', default='Activo', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
            options={
                'db_table': 'tipos_colaborador',
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha de actualización')),
                ('descripcion', models.TextField(blank=True, db_comment='Descripción', default=None, null=True)),
                ('value', models.CharField(db_comment='Valor', max_length=5, primary_key=True, serialize=False)),
                ('status', models.ForeignKey(blank=True, db_comment='Estado', default='Activo', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
            options={
                'db_table': 'tipos_identificacion',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha de actualización')),
                ('numero_id', models.CharField(db_comment='Numero identifacion de la persona', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_comment='Nombre de la persona')),
                ('password', models.TextField(db_comment='Contraseña del usuario')),
                ('status', models.ForeignKey(blank=True, db_comment='Estado', default='Activo', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
                ('tipo_id', models.ForeignKey(db_comment='Tipo de identificación', default='CC', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.tipoidentificacion')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha de actualización')),
                ('name', models.CharField(db_comment='Nombre', max_length=100)),
                ('status', models.ForeignKey(blank=True, db_comment='Estado', default='Activo', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
            options={
                'db_table': 'tipos_vehiculos',
            },
        ),
        migrations.CreateModel(
            name='VehiculosUsuario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha de actualización')),
                ('pk', models.CompositePrimaryKey('usuario_id', 'placa', blank=True, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(db_comment='Placa del vehiculo', max_length=10, unique=True)),
                ('status', models.ForeignKey(blank=True, db_comment='Estado', default='Activo', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipovehiculo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehiculos_usuario',
            },
        ),
        migrations.AddConstraint(
            model_name='usuarios',
            constraint=models.UniqueConstraint(fields=('numero_id', 'tipo_id'), name='unico_tipo_numero'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usuarios',
            trigger=pgtrigger.compiler.Trigger(name='prevenir_password_sin_hash', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (NOT (NEW."password"::text LIKE \'pbkdf2\\_%\'))', func="RAISE EXCEPTION 'pgtrigger: Cannot insert or update rows from % table', TG_TABLE_NAME;", hash='42dd3d4c352ce5e061b6e54f5643046711ff4506', operation='INSERT OR UPDATE', pgid='pgtrigger_prevenir_password_sin_hash_49d93', table='usuarios', when='BEFORE')),
        ),
    ]
