# Generated by Django 5.2.7 on 2026-05-01 01:45

import django.contrib.postgres.constraints
import django.core.validators
import django.db.models.deletion
import psqlextra.manager.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [

        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Franquicias',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha de actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_verificacion', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('razon_social', models.CharField(blank=True, max_length=225, null=True)),
                ('nombre', models.CharField(db_comment='nombre para mostrar en la app', max_length=120)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dueno_franquicias', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, db_comment='Estado', default='Activo', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
            options={
                'db_table': 'franquicias',
            },
        ),
        migrations.CreateModel(
            name='ColaboradresFranquicia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha de actualización')),
                ('pk', models.CompositePrimaryKey('franquicia_id', 'usuario_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('status', models.ForeignKey(blank=True, db_comment='Estado', default='Activo', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
                ('tipo_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipocolaborador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='franquicias', to=settings.AUTH_USER_MODEL)),
                ('franquicia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colaboradores', to='negocios.franquicias')),
            ],
            options={
                'db_table': 'colaboradores_franquicia',
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha de actualización')),
                ('nit', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('numero_verificacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('razon_social', models.CharField(max_length=225)),
                ('nombre', models.CharField(db_comment='nombre para mostrar en la app', max_length=120)),
                ('minutos_gracia', models.IntegerField(blank=True, db_comment='Minutos de cortesía antes de cobrar la siguiente fracción', default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dueno_negocios', to=settings.AUTH_USER_MODEL)),
                ('franquicia', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='negocios', to='negocios.franquicias')),
                ('status', models.ForeignKey(blank=True, db_comment='Estado', default='Activo', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
            options={
                'db_table': 'negocios',
            },
        ),
        migrations.CreateModel(
            name='ColaboradoresNegocio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha de actualización')),
                ('pk', models.CompositePrimaryKey('negocio_id', 'usuario_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('status', models.ForeignKey(blank=True, db_comment='Estado', default='Activo', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
                ('tipo_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipocolaborador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='negocios', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colaboradores', to='negocios.negocio')),
            ],
            options={
                'db_table': 'colaboradores_negocio',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha de actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_comment='Nombre de la sede (ej: Sede Norte)', max_length=120)),
                ('direccion', models.TextField(db_comment='Dirección física')),
                ('lat', models.DecimalField(blank=True, db_comment='Latitud GPS', decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, db_comment='Longitud GPS', decimal_places=7, max_digits=10, null=True)),
                ('minutos_gracia', models.IntegerField(blank=True, db_comment='Minutos de cortesía antes de cobrar la siguiente fracción', default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cities')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.countries')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dueno_sedes', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(db_comment='Negocio al que pertenece esta sede', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sedes', to='negocios.negocio')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.states')),
                ('status', models.ForeignKey(blank=True, db_comment='Estado', default='Activo', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
            options={
                'db_table': 'sedes',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha de actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField(db_comment='Descripcion de la reseña')),
                ('puntuacion', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),

                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resenas', to='negocios.negocio')),
                ('status', models.ForeignKey(blank=True, db_comment='Estado', default='Activo', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resenas', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resenas', to='negocios.sede')),
            ],
            options={
                'db_table': 'resenas',
            },
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha de actualización')),
                ('pk', models.CompositePrimaryKey('sede_id', 'piso', 'numero', 'tipo_vehiculo', blank=True, editable=False, primary_key=True, serialize=False)),
                ('piso', models.CharField(db_comment="Piso (ej: '1', 'B1', 'Sótano')", max_length=20)),
                ('numero', models.IntegerField(db_comment='Número del puesto', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.ForeignKey(blank=True, db_comment='Estado', default='Activo', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipovehiculo')),
                ('sede', models.ForeignKey(db_comment='Sede donde está el puesto', on_delete=django.db.models.deletion.PROTECT, related_name='puestos', to='negocios.sede')),
            ],
            options={
                'db_table': 'puestos',
            },
        ),
        migrations.CreateModel(
            name='ColaboradoresSede',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha de actualización')),
                ('pk', models.CompositePrimaryKey('sede_id', 'usuario_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('status', models.ForeignKey(blank=True, db_comment='Estado', default='Activo', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
                ('tipo_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipocolaborador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sedes', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colaboradores', to='negocios.sede')),
            ],
            options={
                'db_table': 'colaboradores_sede',
            },
        ),
        migrations.CreateModel(
            name='Tarifas',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha de actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('piso', models.CharField(blank=True, db_comment='Piso específico (null = aplica a toda la sede)', max_length=20, null=True)),
                ('numero', models.IntegerField(blank=True, db_comment='Número de puesto específico (null = aplica al piso)', default=None, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('tiempo', models.DurationField(db_comment='Fracción de tiempo (ej: 1h, 30min)')),
                ('valor', models.DecimalField(db_comment='Valor en COP', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='negocios.negocio')),
                ('puesto', models.ForeignObject(blank=True, from_fields=('sede_id', 'piso', 'numero', 'tipo_vehiculo_id'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarifas_puesto', to='negocios.puestos', to_fields=('sede_id', 'piso', 'numero', 'tipo_vehiculo_id'))),
                ('sede', models.ForeignKey(blank=True, db_comment='Sede específica (null = aplica a todo el negocio)', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='negocios.sede')),
                ('status', models.ForeignKey(blank=True, db_comment='Estado', default='Activo', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipovehiculo')),
            ],
            options={
                'db_table': 'tarifas',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha de actualización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('piso', models.CharField(db_comment='piso donde se encuentra el puesto', max_length=20)),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tiempo', models.DurationField(blank=True, db_comment='Tiempo de la tarifa', null=True)),
                ('placa', models.CharField(db_comment='Placa del vehiculo', max_length=10)),
                ('hf_inicio', models.DateTimeField(db_comment='Fecha y hora de inicio de la reserva')),
                ('hf_final', models.DateTimeField(blank=True, db_comment='Fecha y hora de fin de la reserva', null=True)),
                ('valor_total', models.DecimalField(blank=True, db_comment='Valor total generado por la reserva (según tarifas)', decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_pagado', models.DecimalField(blank=True, db_comment='Valor total pagado de la reserva', decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_transferencia', models.DecimalField(blank=True, db_comment='Valor pagado por transferencia', decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_tarjeta', models.DecimalField(blank=True, db_comment='Valor pagado por tarjeta', decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_efectivo', models.DecimalField(blank=True, db_comment='Valor pagado en efectivo', decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),

                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='negocios.negocio')),
                ('puesto', models.ForeignObject(from_fields=('sede_id', 'piso', 'numero', 'tipo_vehiculo_id'), on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='negocios.puestos', to_fields=('sede_id', 'piso', 'numero', 'tipo_vehiculo_id'))),
                ('status', models.ForeignKey(blank=True, db_comment='Estado', default='Activo', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipovehiculo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignObject(from_fields=('usuario_id', 'placa'), on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='core.vehiculosusuario', to_fields=('usuario_id', 'placa'))),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='negocios.sede')),
                ('tarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='negocios.tarifas')),
            ],
            options={
                'db_table': 'reservas',
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='franquicias',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('nit__isnull', True), ('numero_verificacion__isnull', True), ('razon_social__isnull', True)), models.Q(('nit__isnull', False), ('numero_verificacion__isnull', False), ('razon_social__isnull', False)), _connector='OR'), name='validar_datos_franquicia_completos'),
        ),
        migrations.AddConstraint(
            model_name='colaboradresfranquicia',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_colaborador', '-1')), fields=('franquicia', 'tipo_colaborador'), name='unico_dueno_franquicia'),
        ),
        migrations.AddConstraint(
            model_name='negocio',
            constraint=models.UniqueConstraint(fields=('nit', 'numero_verificacion'), name='unico_codigo_verf_negocio'),
        ),
        migrations.AddConstraint(
            model_name='colaboradoresnegocio',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_colaborador', '-1')), fields=('negocio', 'tipo_colaborador'), name='unico_dueno_negocio'),
        ),
        migrations.AddConstraint(
            model_name='colaboradoressede',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_colaborador', '-1')), fields=('sede', 'tipo_colaborador'), name='unico_dueno_sede'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['Reservado', 'Activo'])), expressions=(('negocio', '='), ('sede', '='), ('piso', '='), ('numero', '='), ('tipo_vehiculo', '=')), name='en'),
        ),
    ]
