# Generated by Django 5.2.7 on 2026-05-01 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='cliente',
            field=models.ForeignObject(blank=True, default=None, from_fields=('negocio_id', 'usuario_id'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resenas', to='clientes.clientenegocio', to_fields=('negocio_id', 'usuario_id')),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignObject(blank=True, from_fields=('negocio_id', 'usuario_id'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='clientes.clientenegocio', to_fields=('negocio_id', 'usuario_id')),
        ),
    ]
