"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os, platform
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mne%*rxggu5!_nbq48c)n%a9y%wc0f2#$lnmr^ga*two!4b0qc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ('true', '1', 'yes')

HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS").split(',')
ALLOWED_HOSTS = list(set(
    host.split(':')[0]
    for host in HOSTS    
))

OS_ACTUAL = platform.system()

# Application definition
AUTH_USER_MODEL = 'core.Usuarios'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Librerias
    'corsheaders', # habilitar servidores que puedan consultar
    'pgtrigger', # disparadores de postgresql
    'django_extensions', # mas utilidades de django, mas en consola
    # 'django_tenants', # multitenancia, varios schemas
    'import_export', # exportar e importar datos e modelos
    'rest_framework', # api rest
    'rest_framework_simplejwt', # api rest con auth
    'rest_framework_simplejwt.token_blacklist', # black list de la api rest auth
    'django_filters', # filtros en direccion con api rest
    'csp',
    
    # Apps
    'core',
    'clientes',
    'negocios',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Controladores de datos
    # 'config.controllers.middlewares.CurrentUserMiddleware',
]

ROOT_URLCONF = 'config.urls'
APPEND_SLASH = False

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'psqlextra.backend',
        'NAME': os.getenv('DJANGO_DB_NAME'),
        'HOST': os.getenv('DJANGO_DB_HOST'),
        'PORT': os.getenv('DJANGO_DB_PORT'),
        'USER': os.getenv('DJANGO_DB_USER'),
        'PASSWORD': os.getenv('DJANGO_DB_PASS'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-CO'

TIME_ZONE = 'America/Bogota'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

WHITENOISE_KEEP_ONLY_HASHED_FILES = True
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG 
WHITENOISE_MAX_AGE = 14400 # Cache por 4 horas 

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = '/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CELERY CONFIGS
# CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
# CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
# CELERY_ACCEPT_CONTENT = ["json"]
# CELERY_TASK_SERIALIZER = "json"
# CELERY_RESULT_SERIALIZER = "json"

# REST FRAMEWORK
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # 'PAGE_SIZE': 1,
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'rest_framework.throttling.AnonRateThrottle',  # Usuarios anónimos
    #     'rest_framework.throttling.UserRateThrottle',  # Usuarios logueados
    #     'rest_framework.throttling.ScopedRateThrottle',  # Por scope
    #     'config.controllers.throttling.AppRateThrottle',  # Apps
    #     'config.controllers.throttling.BurstRateThrottle',  # Ráfaga
    #     'config.controllers.throttling.SafeEndpointThrottle',  # Endpoints sensibles
    # ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     'anon': '10/day',     # Anónimos
    #     'user': '1000/day',    # Usuarios
    #     'app': '1000/hour',    # Apps
    #     'burst': '100/minute',  # Ráfaga
    #     'safe': '10/minute', # Endpoints sensibles
    # },
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    # "TOKEN_OBTAIN_SERIALIZER": "config.auth.serializers.CustomObtainPairSerializer",
    
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'USER_ID_FIELD': 'numero_id',
    'USER_ID_CLAIM': 'numero_id',
}

# CORS HEADERS
from corsheaders.defaults  import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    # 'Authorization', 'App-ApiKey'
]
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED = [
    f'{scheme}://{host_port}'
    for host_port in HOSTS
    for scheme in ('http', 'https')
]
CORS_ALLOWED_ORIGINS = CORS_ALLOWED

# SESSION COOKIES
SESSION_COOKIE_SAMESITE = (
    "Strict" if not DEBUG else "Lax"
)  # Maxima seguridad en produccion - seguridad necesaria en desarrollo
SESSION_COOKIE_SECURE = not DEBUG  # Solo HTTPS
SESSION_COOKIE_HTTPONLY = True  # Proteccion XSS

# CSRF
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED
CSRF_COOKIE_SAMESITE = "Lax"  # Tipo de seguridad en las cookies
CSRF_COOKIE_SECURE = not DEBUG  # Seguridad de las cookies

# CSP
# CSP_FRAME_ANCESTORS = ["'self'"] + CORS_ALLOWED
CONTENT_SECURITY_POLICY = {"DIRECTIVES": {"frame-ancestors": ["'self"] + CORS_ALLOWED}}

# LOGS  
LOG_DIR = (BASE_DIR / 'logs')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'access': {
            'format': '[{asctime}] {method} {path} {status_code} {remote_addr} {user_agent} {message}', 
            'style': '{',
        },
    },
    'handlers': {
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': LOG_DIR / 'error.log',
            'formatter': 'verbose',
        },
        'access_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': LOG_DIR / 'access.log',
            'formatter': 'access',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django.server': {
            'handlers': ['access_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        }
    },
}