# Generated by Django 5.2.7 on 2026-05-01 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('negocios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteNegocio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Fecha de actualización')),
                ('pk', models.CompositePrimaryKey('negocio_id', 'usuario_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clientes', to='negocios.negocio')),
                ('status', models.ForeignKey(blank=True, db_comment='Estado', default='Activo', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente_negocio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientes_negocio',
            },
        ),
    ]
